### ISSUE TITLE
Track id

### ISSUE THREAD

**Issue by keqizero** [egeozsoy/4D-OR#5]
Hi, I have a question about the track id. I saw that the track id can go up to almost 20 in each sequence, but obviously there isn't that much of person according to the human name. Therefore, may I ask how did you define the track id? And do you recommend using the human name or the track id to conduct the tracking task? Thank you!

**Comment by egeozsoy** [comment]
The "track" as we define in the dataset might be lost if a human exits the scene and enters again etc. We are not doing any re-identification at this stage. The tracking and therefore the track id is based on rather simple matching between two consecutive timepoints. 

However the human role names are consistent throughout the sequence, so the track ids 0, 5 and 12 might all correspond to the same human. 

The decision of using the track id vs human role names depends on the concrete task you have in mind. The human names might provide you with a more consistent label that stays constant throughout the sequence, which is likely what you are looking for.

**Comment by keqizero** [comment]
> The "track" as we define in the dataset might be lost if a human exits the scene and enters again etc. We are not doing any re-identification at this stage. The tracking and therefore the track id is based on rather simple matching between two consecutive timepoints.
> 
> However the human role names are consistent throughout the sequence, so the track ids 0, 5 and 12 might all correspond to the same human.
> 
> The decision of using the track id vs human role names depends on the concrete task you have in mind. The human names might provide you with a more consistent label that stays constant throughout the sequence, which is likely what you are looking for.

Understood. Thank you so much!
